---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: oomkill-exporter
  labels:
    app: oomkill-exporter
spec:
  selector:
    matchLabels:
      app: oomkill-exporter
  template:
    metadata:
      labels:
        app: oomkill-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
    spec:
      containers:
      - name: oomkill-exporter
        image: gari123/kubernetes-oomkill-exporter:latest
        imagePullPolicy: Always
        args:
        - -logtostderr
        - -v=5
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 20m
            memory: 20Mi
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
             fieldPath: spec.nodeName
        volumeMounts:
        - name: kmsg
          mountPath: /dev/kmsg
          readOnly: true
        ports:
        - name: metrics
          containerPort: 9102
      volumes:
      - name: kmsg
        hostPath:
          path: /dev/kmsg
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: oomkill-exporter
subjects:
- kind: ServiceAccount
  name: oomkill-exporter
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: oomkill-exporter
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: oomkill-exporter
  labels:
    k8s-app: oomkill-exporter
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs:
  - get
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oomkill-exporter
  namespace: kube-system
  labels:
    k8s-app: oomkill-exporter

